### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'split'

### ISSUE THREAD

**Issue by okiwoki** [Mr-Un1k0d3r/CatMyPhish#2]
Getting this error when attempting to use the tool now:

# python CatMyFish.py chicken
CatMyFish v1.0 - Search for available already categorized domain
Mr.Un1k0d3r - RingZer0 Team 2016

Traceback (most recent call last):
  File "CatMyFish.py", line 125, in <module>
    hosts = get_hosts_from_keywords(keywords)
  File "CatMyFish.py", line 24, in get_hosts_from_keywords
    response.info().getheader("Set-Cookie").split("ExpiredDomainssessid=")[1].split(";")[0] + "; urih="
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by Mr-Un1k0d3r** [comment]
I've updated the code since the website doesn't require the cookie anymore
